# Generated by Django 5.2.12 on 2026-03-23 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('intitule', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=2)),
                ('niveau', models.CharField(choices=[('L1S1', 'L1 - Semestre 1'), ('L1S2', 'L1 - Semestre 2'), ('L2S3', 'L2 - Semestre 3'), ('L2S4', 'L2 - Semestre 4')], default='L1S1', max_length=10)),
                ('cmi', models.IntegerField(default=0, help_text='Cours Magistraux Intégrés')),
                ('td', models.IntegerField(default=0, help_text='Travaux Dirigés')),
                ('tp', models.IntegerField(default=0, help_text='Travaux Pratiques')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['niveau', 'code', 'intitule'],
            },
        ),
        migrations.CreateModel(
            name='CreateurProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('titre', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='createur/')),
                ('competences', models.TextField(blank=True, help_text='Compétences séparées par des virgules')),
                ('site_web', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('projet_cerebro_desc', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='createur_profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_session', models.CharField(default='Session principale', max_length=100)),
                ('heures_par_semaine', models.FloatField(default=10.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamenCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examen', models.DateField()),
                ('note_actuelle', models.FloatField(help_text='Note actuelle sur 20')),
                ('note_cible', models.FloatField(help_text='Note cible sur 20')),
                ('maitrise', models.IntegerField(default=3, help_text='Niveau de maîtrise de 0 à 5')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cours')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_examens', to='core.examensession')),
            ],
            options={
                'ordering': ['date_examen'],
            },
        ),
        migrations.CreateModel(
            name='ProfilEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('L1S1', 'L1 - Semestre 1'), ('L1S2', 'L1 - Semestre 2'), ('L2S3', 'L2 - Semestre 3'), ('L2S4', 'L2 - Semestre 4')], default='L1S1', max_length=10)),
                ('heures_par_semaine', models.FloatField(default=10.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_actuelle', models.FloatField(help_text='Note actuelle sur 20')),
                ('note_cible', models.FloatField(help_text='Note cible sur 20')),
                ('difficulte', models.IntegerField(default=3, help_text='Difficulté de 0 à 5')),
                ('urgence', models.IntegerField(default=3, help_text='Urgence de 0 à 5')),
                ('heures_par_semaine', models.FloatField(default=10.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cours')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_revision', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
