# Generated by Django 5.2.12 on 2026-04-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiopresentation_profiletudiant_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createurprofil',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature manuscrite (PNG fond transparent ou fond blanc) — apparaîtra sur tous les PDFs', null=True, upload_to='signatures/'),
        ),
    ]
